auth-service:
  build: { context: ./auth-service }
  container_name: auth-service
  environment:
    - JWT_SECRET=UmaSenhaLongaParaGerarHash
  ports:
    - "8081:8080"
  depends_on: [service-discovery]
  networks: [app-network]

bets-service:
  build: { context: ./bets-service }
  container_name: bets-service
  ports:
    - "8082:8080"
  depends_on: [service-discovery]
  networks: [app-network]

matches-service:
  build: { context: ./matches-service }
  container_name: matches-service
  ports:
    - "8084:8080"
  depends_on: [service-discovery]
  networks: [app-network]
